[2021-05-17 07:25:39,734] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: etl_postgresql2mongo.read_from_MongoDB 2021-05-17T07:20:00+00:00 [queued]>
[2021-05-17 07:25:39,748] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: etl_postgresql2mongo.read_from_MongoDB 2021-05-17T07:20:00+00:00 [queued]>
[2021-05-17 07:25:39,748] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 07:25:39,748] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-05-17 07:25:39,748] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 07:25:39,755] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): read_from_MongoDB> on 2021-05-17T07:20:00+00:00
[2021-05-17 07:25:39,758] {standard_task_runner.py:52} INFO - Started process 90 to run task
[2021-05-17 07:25:39,761] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl_postgresql2mongo', 'read_from_MongoDB', '2021-05-17T07:20:00+00:00', '--job-id', '25', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/csv_postgres_2_mongo.py', '--cfg-path', '/tmp/tmp2t9gy_wc', '--error-file', '/tmp/tmpp2z11pjd']
[2021-05-17 07:25:39,761] {standard_task_runner.py:77} INFO - Job 25: Subtask read_from_MongoDB
[2021-05-17 07:25:39,797] {logging_mixin.py:104} INFO - Running <TaskInstance: etl_postgresql2mongo.read_from_MongoDB 2021-05-17T07:20:00+00:00 [running]> on host d0d96188f4f7
[2021-05-17 07:25:39,830] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=etl_postgresql2mongo
AIRFLOW_CTX_TASK_ID=read_from_MongoDB
AIRFLOW_CTX_EXECUTION_DATE=2021-05-17T07:20:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-17T07:20:00+00:00
[2021-05-17 07:25:39,833] {logging_mixin.py:104} WARNING - /home/airflow/.local/lib/python3.6/site-packages/pymongo/topology.py:162 UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: https://pymongo.readthedocs.io/en/stable/faq.html#is-pymongo-fork-safe
[2021-05-17 07:25:39,847] {logging_mixin.py:104} INFO - number of documents in mongoDB =  200
[2021-05-17 07:25:39,847] {python.py:118} INFO - Done. Returned value was: None
[2021-05-17 07:25:39,855] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=etl_postgresql2mongo, task_id=read_from_MongoDB, execution_date=20210517T072000, start_date=20210517T072539, end_date=20210517T072539
[2021-05-17 07:25:39,878] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-17 07:25:39,892] {local_task_job.py:146} INFO - Task exited with return code 0
