[2021-05-17 07:45:34,934] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: etl_postgresql2mongo.read_from_MongoDB 2021-05-17T07:40:00+00:00 [queued]>
[2021-05-17 07:45:34,950] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: etl_postgresql2mongo.read_from_MongoDB 2021-05-17T07:40:00+00:00 [queued]>
[2021-05-17 07:45:34,951] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 07:45:34,951] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-05-17 07:45:34,951] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-05-17 07:45:34,959] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): read_from_MongoDB> on 2021-05-17T07:40:00+00:00
[2021-05-17 07:45:34,964] {standard_task_runner.py:52} INFO - Started process 290 to run task
[2021-05-17 07:45:34,967] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'etl_postgresql2mongo', 'read_from_MongoDB', '2021-05-17T07:40:00+00:00', '--job-id', '41', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/csv_postgres_2_mongo.py', '--cfg-path', '/tmp/tmp75oiy56d', '--error-file', '/tmp/tmp3v2awpew']
[2021-05-17 07:45:34,967] {standard_task_runner.py:77} INFO - Job 41: Subtask read_from_MongoDB
[2021-05-17 07:45:35,008] {logging_mixin.py:104} INFO - Running <TaskInstance: etl_postgresql2mongo.read_from_MongoDB 2021-05-17T07:40:00+00:00 [running]> on host d0d96188f4f7
[2021-05-17 07:45:35,043] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=etl_postgresql2mongo
AIRFLOW_CTX_TASK_ID=read_from_MongoDB
AIRFLOW_CTX_EXECUTION_DATE=2021-05-17T07:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-17T07:40:00+00:00
[2021-05-17 07:45:35,046] {logging_mixin.py:104} WARNING - /home/airflow/.local/lib/python3.6/site-packages/pymongo/topology.py:162 UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: https://pymongo.readthedocs.io/en/stable/faq.html#is-pymongo-fork-safe
[2021-05-17 07:45:35,060] {logging_mixin.py:104} INFO - number of documents in mongoDB =  600
[2021-05-17 07:45:35,060] {python.py:118} INFO - Done. Returned value was: None
[2021-05-17 07:45:35,069] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=etl_postgresql2mongo, task_id=read_from_MongoDB, execution_date=20210517T074000, start_date=20210517T074534, end_date=20210517T074535
[2021-05-17 07:45:35,094] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-05-17 07:45:35,137] {local_task_job.py:146} INFO - Task exited with return code 0
